import type { Metadata } from "next";
import localFont from "next/font/local";

import "./globals.css";

import { Inter } from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-inter",
  display: "swap",
});

const gotham_black = localFont({
  src: "../fonts/Gotham_Black.otf",
  display: "swap",
  variable: "--font-gotham-black",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${gotham_black.className} ${inter.className} `}>
        {children}
      </body>
    </html>
  );
}
