import type { Metadata } from "next";
import { gotham_black, inter } from "@/fonts";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${gotham_black.className}`}>
        {children}
      </body>
    </html>
  );
}
